# Dhara Robotics — GitHub Pages config
title: Dhara Robotics
description: The world's most capable robotic joint actuator. D1 Drive.
url: "https://aakashluharpanchal.github.io"
baseurl: "/dhara-robotics"
